# Generated by Django 4.0.2 on 2022-05-24 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_asd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asd',
        ),
    ]
