# Generated by Django 4.1.5 on 2023-05-10 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_delete_asd'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_field', models.ImageField(upload_to='images/')),
                ('price', models.IntegerField()),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
