# Generated by Django 4.1.5 on 2023-05-11 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_itemtable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ItemTable',
        ),
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.ImageField(blank=True, upload_to='media/product'),
        ),
    ]
