# Generated by Django 4.1.5 on 2023-05-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_itemtable_alter_products_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='foto',
            field=models.CharField(max_length=200),
        ),
    ]
